### ISSUE TITLE
communication loss to Hummingbird

### ISSUE THREAD

**Issue by devtronslab** [ethz-asl/asctec_mav_framework#32]
Been having some weird issues recently when running  a simple waypoint navigation and was hoping you might be able to shed some light on the issue.

First manifested itself as commands from waypoint_nav being lost halfway through flight pattern. Doesn't happen all the time, but when it does, waypoint_nav shows positional feedback data but Hummingbird doesn't move to the next point. At this point, I kill the waypoint_nav script to prevent an unwanted move to the next point, so I'm not sure if only a single command is being lost or if all subsequent as well. 

Another variation consists of the above mentioned command loss, followed by a movement outside of the tracked Vicon space. Movement is typically slow, and once outside of the tracked area, it continues in a steady motion.

Finally, the wandering described above has also sometimes occurred when the quad is simply hovering. No waypoint commands are sent after the initial takeoff, and after a length of time, the quad will slowly fly out of the tracked area.

No frames seem to be thrown away by the Vicon system, but in one instance there was a "get frame returned false" by the Vicon Bridge. There are, however, many checksum errors from the asctec_hl_interface running on the onboard computer. 

Anything you could point me towards as the source of the problems? Are the checksum errors occurring between the HLP and the onboard computer or bewteen the onboard computer and the server running the roscore?

Setup:
- AscTec Hummingbird with your asctec_hl_firmware 
- Raspberry Pi 2 running Raspbian Jessie as onboard computer
- RasPi2 connected to HL processor via USB Mini cable to AscTec dongle
- Roscore and Vicon Bridge running on 64-bit Ubuntu 14.04LTS 
- RasPi2 communicating with roscore via USB WiFi dongle.

**Comment by markusachtelik** [comment]
hi, first, could it have happened that you touched the sticks of the RC, or they were not centered (e.g. tirmming off). In that case, it stops at the current position. However, that doesn't really explain why this happens halfway in the flight pattern...

I can't see something wrong with your setup, however, we have never tried the rasperry pi. the checksum errors are between HLP and onboard computer. 
The drifting away sounds like localization is lost. Since your vicon seems to be fine, it must get lost somewhere between the raspi and the HLP, maybe together with the position commands. How fast are you sending data to the HLP? Which baudrate did you set? I assume you're using the Luenberger Observer?

**Comment by devtronslab** [comment]
Hi Markus, thanks for your prompt reply.

Only waypoint commands are sent via the waypoint action server, and the timeouts are 30 seconds. Distances to be travelled are roughly 2 meters. Baudrate was left as the default at 460800. The Luenberger observer is indeed used, and none of the values have been changed.

**Comment by devtronslab** [comment]
Also, I am going to try to attempt to isolate the problem by removing the RasPi and running the HL interface on the Ubuntu server, connecting to the Hummingbird with 2 Xbees like you suggest a few different places. 

Could you clarify a couple of points for doing this? Setting ~serial_port to empty and ~serial_port_rx and ~serial_port_tx to the correct port values, does that take place in the fcu_parameters.yaml file and/or rqt_reconfigure? I see a value for fcu/serial_port but none for serial_port_rx or serial_port_tx. 

Also, in order to make use of the second Xbee pair, does the firmware for the HLP need to be updated at all? If not, which port is the default rx and which tx?

**Comment by markusachtelik** [comment]
I think it's safer to set the serial port parameters by yaml file. For isolating the problem, can you try this with a cabled connection over one serial port first? 

two xbees do not need a firmware change. with the xbees, only 57600 baud are possible. Even though two xbees help, you should limit the rates of IMU etc, since it's still a lot of data for that baudrate. 
Each xbee pair takes care of rx and tx respectively. for the tx (seen from the HLP), make sure that the CTS cable is connected to the xbee correctly. The easiest approach is to start from the single setup, add a second one, poser it from the same cable, then connect the rx pin of the HLP to the second xbee. 

on the computer side, you need to find out which xbee belongs to which port. Either connect them always in the same order, or more advanced, I believe you can do some udev scripting based on serial numbers and assign distinct port names

**Comment by devtronslab** [comment]
Ah okay, I was under the impression that the two Xbees were connected to two different ports on the Hummingbird. I understand now what you mean.

After a bit of testing, the problem is most likely either: incorrect baudrate (115200 seems to be much happier than 460800) causing the RasPi2 USB->AscTec serial dongle->HL Serial 0 connection loses sync, or packet loss when communicating with the RasPi2 over WiFi. 

Connecting to the HLP from the Ubuntu server with the USB to AscTec serial cable works fine.

Attempting to run asctec_hl_interface with only one Xbee pair results in timeouts, exactly as described in http://asctec-users.986163.n3.nabble.com/Using-asctec-mav-framework-with-xbee-td4024529.html

Will update once I have results from a flying test without RasPi2.

**Comment by markusachtelik** [comment]
any update on this? can we close?

**Comment by devtronslab** [comment]
It seems likely that this was simply a connection loss, but we haven't been able to fully locate or solve the issue.

We got the dual Xbee setup working, but the connection (even with the IMU data packet rate dropped to 5Hz) was fragile at best. There were numerous resync warnings in asctec_hl_framework, and the connection got less stable with each kill and restart of the interface (while not touching the power of the Hummingbird). On attempting to connect a third time, no packets were received from the HL processor. We never tried to fly using this connection.

This setup was ditched in favor of Bluetooth 2.1 modules, which seemed to give a decently robust connection (WiFi Xbee modules were avoided on purpose). Using these, we were able to test pretty extensively. 

The "wandering" issue still occurs, although quite rarely. When it does, we've never seen any packet timeouts on the asctec_hl_interface, and the resync notifications are no more frequent than when the issue does not occur, but killing vicon_bridge while the Hummingbird is hovering (when the Hummingbird is otherwise operating normally) gives a very similar behavior. 

I would say the original problem was most likely a connection issue between the RasPi2 and roscore, causing a dropout in Vicon data. As for the issues being experienced with the Bluetooth, most likely this is a problem with the data being sent to the Hummingbird (we've had issues with interference before).
